version: '3.8'

services:
  rest-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3307
    ports:
      - 3307:3307
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_TCP_PORT: 3307
    container_name: rest-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3307"]
      interval: 10s
      timeout: 120s
      retries: 11

  rest-backend:
    build: .
    container_name: rest-backend
    ports:
      - 3002:3002
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      rest-database:
        condition: service_healthy
    expose:
      - 3002
    env_file:
      - .env

  redis:
    image: redis:6
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - .:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    env_file:
      - .env